name: Node CI
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8, lts]
        os: [ubuntu-latest]
    env:
      NYC: yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc
      MOCHA_FILE: reports/mocha.xml
    steps:
    - uses: actions/checkout@v2
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn
    - run: yarn add -D nyc@13 @oclif/nyc-config@1 mocha-junit-reporter@1
    - run: |
        mkdir -p reports
        $NYC yarn test --reporter mocha-junit-reporter
        $NYC report --reporter text-lcov > coverage.lcov
    - uses: actions/upload-artifact@v2
      with:
        path: "~/cli/reports"
