name: Node CI
on:
  push:

jobs:
  test:
    runs-on: ${{ matris.os }}
    strategy:
      matrix:
        node-version: [8, lts]
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: "~/cli"
    env:
      NYC: yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc
      MOCHA_FILE: reports/mocha.xml
    steps:
    - uses: actions/checkout@v2
    - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
      ${{ runner.os }}-yarn-
    - run: yarn
    - run: yarn add -D nyc@13 @oclif/nyc-config@1 mocha-junit-reporter@1
    - run: |
        mkdir -p reports
        $NYC yarn test --reporter mocha-junit-reporter
        $NYC report --reporter text-lcov > coverage.lcov
    - uses: actions/upload-artifact@v2
      with:
        path: "~/cli/reports"

  release:
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: "~/cli"
    runs-on: ubuntu-latest
    container:
      image: node:latest
    needs:
    - node-latest
    - node-8
    env:
      NYC: yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc
      MOCHA_FILE: reports/mocha.xml
    steps:
    # Ensure parameter if_key_exists is set correctly
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
        name: circle_ci_id_rsa
        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
        if_key_exists: fail
    - uses: actions/checkout@v2
    - name: restore_cache
      uses: actions/cache@v3
      with:
        key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
        restore-keys: |-
          v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
          v1-yarn-{{checksum ".circleci/config.yml"}}
    - run: yarn global add @oclif/semantic-release@3 semantic-release@15
    - run: yarn --frozen-lockfile
    - run: |
        export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
        semantic-release -e @oclif/semantic-release
    - name: save_cache
      uses: actions/cache@v3
      with:
        path: |-
          ~/cli/node_modules
          /usr/local/share/.cache/yarn
          /usr/local/share/.config/yarn
        key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
