name: publish

on:
  release:
    types: [released]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true
jobs:
  npm:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
    with:
      ctc: false
      sign: false
      tag: latest
      githubTag: ${{ github.event.release.tag_name || inputs.tag }}
    secrets: inherit
  npm-promote:
    needs: [npm]
    runs-on:
      ubuntu-latest
      # if you try to use yarn here, it will attempt to use the wrong registry and throw 401s
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm run promote-dist-tags
